### ISSUE TITLE
Partner Provider Program - Second Review

### ISSUE THREAD

**Issue by cgriggs01** [oktstage/terraform-provider-asa#5]
Hey Team,

Thanks for you work thus far, we are very close to the end. A few more items before we can release. 

- [x] The provider should be using Go Modules for vendoring the required dependancies for the integration. To do this, you will first was to run `GO111MODULE=on go mod init` and then `GO111MODULE=on go mod vendor` to download the dependancies to the local directory. 

- [x] If main.tf is an example implementation of the provider, it should be kept under a `examples/` directory. 

- [x] The binary that you have build uploaded to `terraform.d/plugins/linux_amd64/terraform-provider-asa` needs to be removed. All binaries for this provider once released will be published at releases.hashicorp.com. 

- [x] In the provider documentation page for [enrollment token](https://github.com/oktstage/terraform-provider-oktaasa/blob/master/website/docs/r/oktaasa_enrollment_token.html.md) the '.' on line 7 must be removed to resolve a formatting issue for the website. 

- [x] In the create_group resource, you have an argument “group_role” that is commented out and unused, this should be removed along with the corresponding calls in the rest of the resource functions. 

- [x] The enrollment_token argument description is capitalized in the documentation and should be made lowercase. Looks like a simple typo from the argument declaration which is lowercase.

**Comment by nlam8191** [comment]
Please clarify last issue #6.

**Comment by cgriggs01** [comment]
All feedback as been address, closing this issue. Thanks for your work on this!
